app_service_plan_name = "test001-ten-app-plan"
location = "westeurope"
resource_group_name = "AZ-RG-NE99WE-ThomasRufyri-POC"
app_plan_kind = "Linux"
app_plan_reservation = "true"
sku_tier = "Standard"
sku_size = "S1"
